### ISSUE TITLE
Some groups not visible in Zeus

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/TheseusServices#107]
**Arma 3 Version:** `1.92` (stable)
**Theseus Services Version:** `1.9.0` (stable)

**Mods:**
```
- theseus_services
- Theseus Inc. Modpack
```

**Description:**
- Some groups are not visible in Zeus:
  - Team
  - Squad
  - Specialists

**Steps to reproduce:**
- Open Zeus

**Where did the issue occur?**
- N/A

**RPT log file:**
- N/A

![Untitled](https://user-images.githubusercontent.com/7935003/60545773-23655780-9d1c-11e9-8aed-3420b18bb3a9.png)

**Comment by TyroneMF** [comment]
- Fix #110
