### ISSUE TITLE
Improve VIP model

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/TheseusServices#15]
Works fine when binarized, in non-binarized the following errors are logged:
- ST generation
- VIEW_PILOT ST generation
- weights
- opposite edges not found
- degenerated faces in shadow(0)
- warnings in shadow(1000)

**Comment by jonpas** [comment]
Even when binarized shadows are weird.

**Comment by Mike-MF** [comment]
Just spent an hour fiddling around with the model to try and fix some rogue shadows it has. Can't actually find what's causing it and if everything listed is still an issue this model might just be a total loss.

Could be worth just `scope = 1` and letting people use the AoW suits.

**Comment by JoramD0** [comment]
Closed by #202
