### ISSUE TITLE
Make new UI pictures

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/TheseusServices#19]
- [x] Backpacks (256*256) #21
- [x] Headgear (256*256) #21
- [ ] Uniforms (256*256) #27 
- [x] Vests (256*256) #21
- [x] Weapons (1024*512) 2a00fae937380c314489073cecb31a8a0a678d08
- [x] Theseus Inc. Flag (1024*512) 7b00ec4dda7612cca2d5d1bc032ce2ec1c224a46

**Comment by SyMP2005** [comment]
Provide and I shall... Re-provide?

I'll help :smile:
