### ISSUE TITLE
Incorrect names of clothing

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/TheseusServices#28]
**Arma 3 Version:** `1.56` (stable)
**Theseus Services Version:** `0.9.0` (stable)

**Mods:**
- `@theseus_services`

**Description:**
- Display names of some clothes are wrong

**Steps to reproduce:**
- Go into VA and hover over said clothes

**Where did the issue occur?**
- Virtual Arsenal

**RPT log file:**
- Nope

**List to change**
- `T-Shirt & Jeans (Blue Shirt & Tan Pants & Black Boots)` TO `T-Shirt & Jeans (Blue Shirt & Blue Pants & Black Boots)`
- `Tactical Clothes (Blue Shirt & Green Pants & Black Boots)` TO `Tactical Clothes (White Shirt & Tan Pants & Black Boots)`
- `Tactical Clothes (Blue Shirt & Green Pants & Black Boots)` TO `Tactical Clothes (Tan Shirt & Blue Pants & Black Boots)`
- `Tactical Clothes (Blue Shirt & Green Pants & Black Boots)` TO `Tactical Clothes (White Shirt & Green Pants & Black Boots)`
- `Tactical Clothes (Blue Shirt & Green Pants & Black Boots)` TO `Tactical Clothes (White Shirt & Blue Pants & Black Boots)`
- `Tactical Clothes (Blue Shirt & Green Pants & Black Boots)` TO `Tactical Clothes (Tan Shirt & Tan Pants & Black Boots)`
- `Tactical Clothes (Blue Shirt & Green Pants & Black Boots)` TO `Tactical Clothes (Green Shirt & Tan Pants & Tan Boots)`
- `Combat Garment Long Sleeves (Black Shirt & Grey Pants & Tan Boots)` TO `Combat Garment Long Sleeves (Brown Shirt & Grey Pants & Tan Boots)`
- `Combat Garment Long Sleeves (Black Shirt & Tan Pants & Tan Boots)` TO `Combat Garment Long Sleeves (Brown Shirt & Tan Pants & Tan Boots)`
- `Combat Garment Rolled Sleeves (Black Shirt & Grey Pants & Tan Boots)` TO `Combat Garment Rolled Sleeves (Brown Shirt & Grey Pants & Tan Boots)`
- `Combat Garment Rolled Sleeves (Black Shirt & Tan Pants & Tan Boots)` TO `Combat Garment Rolled Sleeves (Brown Shirt & Tan Pants & Tan Boots)`
- `Combat Uniform Long Sleeves (Green Shirt & Tan Pants & Tan Boots` TO `Combat Uniform Long Sleeves (Green Shirt & Tan Pants & Black Boots`

**Comment by System98** [comment]
Names (english & german) should be fixed in PR #29. Classnames need to be changed as well tough.
