### ISSUE TITLE
Wrong uniform colors in UI pictures

### ISSUE THREAD

**Issue by System98** [Theseus-Aegis/TheseusServices#31]
**Arma 3 Version:** `1.56` (stable)
**Theseus Services Version:** `0.9.0` (stable)

**Mods:**
- `@theseus_services`
- Rest of Theseus Inc. Modpack

**Description:**
- Some preview pictures in Arsenal of the uniform colors are wrong:

Brownish Shirt instead of black:
Combat Uniform Long Sleeves (Black Shirt & Digital Green Pants & Tan Boots)
Combat Uniform Long Sleeves (Black Shirt & Green Pants & Black Boots) 
Combat Uniform Long Sleeves (Black Shirt & Green Pants & Tan Boots)
Combat Uniform Long Sleeves (Black Shirt & Tan Pants & Black Boots) 
Combat Uniform Long Sleeves (Black Shirt & Tan Pants & Tan Boots) 
 --> example pic for the whole bunch:  http://abload.de/img/1coatj.jpg

Tan Shirt instead of green:
Combat Uniform Long Sleeves (Green Shirt & Black Pants & Black Boots)
Combat Uniform Long Sleeves (Green Shirt & Tan Pants & Black Boots)
--> http://abload.de/img/2c8bqc.jpg & http://abload.de/img/3b7zjb.jpg

Tan Shirt instead of green:
Combat Uniform Rolled Sleeves (Green Shirt & Black Pants & Black Boots)
Combat Unfiorm Rolled Sleeves (Green Shirt & Tan Pants & Black Boots)
--> http://abload.de/img/45dahs.jpg & http://abload.de/img/5uoymz.jpg

Reference pic (correct green color shown in UI picture):
--> http://abload.de/img/6-reference-pic3jyht.jpg

**Steps to reproduce:**
- Start the game, join Virtual Arsenal and compare the UI pictures' uniform colors with the selected uniform on the player.

**Where did the issue occur?**
- Virtual Arsenal

**RPT log file:**
- None needed.

**Comment by jonpas** [comment]
Those are all copied directly from PG Services, all need new pictures. @SyMP2005 you going to handle that?

**Comment by SyMP2005** [comment]
Sure, what exactly do you need?

**Comment by jonpas** [comment]
Pictures for the above.

**Comment by SyMP2005** [comment]
I don't get it, the colors are correct, they're just lighter...

You want me to redo them regardless?

**Comment by jonpas** [comment]
If there are duplicates for any then yes I'd like them redone, if it's just a different accent of the colour and no other is exactly the same, leave it.

**Comment by jonpas** [comment]
Fixed in #87 and #88. If some are left, make separate issues or pull request fixes.
