### ISSUE TITLE
Uniforms randomly get insignia applied as texture

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/TheseusServices#36]
**Arma 3 Version:** `1.56` (stable)
**Theseus Services Version:** `1.0.0` (stable)

**Mods:**
- `@theseus_services`
- Rest of Theseus Inc. Modpack

**Description:**
- Randomly some uniforms get the insignia applied as their texture.

**Steps to reproduce:**
- No idea

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- N/A

**Comment by jonpas** [comment]
Vanilla bug: https://feedback.bistudio.com/T121570

**Comment by SyMP2005** [comment]
hahahahahhah

**Comment by jonpas** [comment]
Not an issue with this mod.
