### ISSUE TITLE
Theseus MX Rifles missing in Arsenal list

### ISSUE THREAD

**Issue by Gabrielite** [Theseus-Aegis/TheseusServices#62]
**Arma 3 Version:** `1.68 - 1.72` (stable)
**Theseus Services Version:** `Workshop 1.2.1.5?` (stable)

**Mods:**
```
- theseus_services
```

**Description:**
- Since maybe 1.68, the Theseus MX rifles that come with the addon were missing from normal Arsenal selection. The did appear from spawned Theseus units and could even be saved that way through Zeus/Arsenal commands. They then did appear in the list but would disappear if you swapped weapons.
- Since 1.72 weapons don't appear in the list or from saved profiles. Using Zeus/Arsenal peeks at units shows the correct weapon in the hands but the Arsenal list shows standard MX equivalent.

**Steps to reproduce:**
- Open virtual arsenal, look at MX rifles. Theseus rifles not to be found.
- Open any saved VA profiles that had Theseus rifles, will see standard MX equivalent in it's place.
- Alternatively, open VA/mission/editor/whatever > use Zeus to spawn Theseus unit > use Zeus command to look at Arsenal on a unit > see Unit hold Theseus MX rifle, but rifle is listed as standard MX equivalent when previously there were entries for the Theseus version.

Tested with *only* Theseus Services loaded.

**Where did the issue occur?**
- Virtual Arsenal Arma v1.68-1.72
- Technically the last update to Theseus was in February and the 1.68 update came out in March. So I don't really know which update started the issue but I noticed it around 1.68 since updates make me double check arsenal profiles to see what broke. 

**Are you sure you aren't just a bad?**
- Pretty sure - picture proof: Zeus/Arsenal looking at a unit, https://i.imgur.com/ZrR3sJM.jpg
- I was going to just leave a simple steam workshop comment but figured this would be the better place to inform since no one brought it up there or here.

**Comment by jonpas** [comment]
@Gabrielite This is definitely a better place to report an issue. :)
