### ISSUE TITLE
Assault Pack Expanded LOD issue

### ISSUE THREAD

**Issue by JoramD0** [Theseus-Aegis/TheseusServices#85]
**Arma 3 Version:** `1.84` (stable)
**Theseus Services Version:** `1.4.0` (stable)

**Mods:**
```
- theseus_services
- Theseus modpack
```

**Description:**
- "Assault pack expanded (Black)" has issues with LODs. It turns green when someone goes farther away and also when you look over your shoulder.

**Steps to reproduce:**
- Grab a "Assault pack expanded (Black)", put it on and look over your shoulder.

**Where did the issue occur?**
- Dedicated (not tested elsewhere)

**RPT log file:**
- [link](https://gist.github.com/JoramD0/f6d4eb1db8499b51120621096b4d00dd)

**Comment by JoramD0** [comment]
Issue made on Arma 3 feedback tracker: https://feedback.bistudio.com/T131466

**Comment by jonpas** [comment]
:tada: Will leave open to confirm on stable.

**Comment by jonpas** [comment]
Fixed by BI.
