### ISSUE TITLE
Feature Request - Add OPFOR faction as well

### ISSUE THREAD

**Issue by Will-Nichols** [Theseus-Aegis/TheseusServices#95]
From a role playing standpoint having this faction as an OPFOR group would be a great addition and would eliminate the extra work of building configs or changing things in the ORBAT Creator to make an OPFOR faction be able to work. This would also eliminate another mod as a dependency in order to have an OPFOR that wasn't necessarily another true military but was more of a group that functions as a go between for the CSAT.

**Comment by JoramD0** [comment]
As Theseus doesn't work with opfor this is out of the scope for this project. You can use something like this to change a units side `[this] joinSilent createGroup EAST;` (taken from comment on the [BI Wiki](https://community.bistudio.com/wiki/setSide))

**Comment by jonpas** [comment]
As said by @JoramD0, same reason eg. BWMod doesn't provide OPFOR factions. You can provide a patch PBO that adds them or use what @JoramD0 wrote in above comment to change them on mission start.

Closing as out of scope.

**Comment by Will-Nichols** [comment]
`[this] joinSilent createGroup EAST;` That piece of "code" is problematic at best.
